export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Navbar} from './navbar'
export {default as Main} from './Main'
export {default as Detail} from './Detail'
export {default as CreateArticle} from './CreateArticle'
export {default as EditArticle} from './EditArticle'
export {default as Error404} from './Error404'